// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    HTTPValidationError,
} from '../models';

export interface ApplyImageTextAsciifyPostRequest {
    image: Blob;
    model?: ApplyImageTextAsciifyPostModelEnum;
}

/**
 * no description
 */
export class ImageTextAsciifyApi extends BaseAPI {

    /**
     * Apply model for the asciify task for a given models
     */
    applyImageTextAsciifyPost(requestParameters: ApplyImageTextAsciifyPostRequest): Observable<object> {
        if (requestParameters.image === null || requestParameters.image === undefined) {
            throw new RequiredError('image','Required parameter requestParameters.image was null or undefined when calling applyImageTextAsciifyPost.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.model !== undefined && requestParameters.model !== null) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: HttpHeaders = {};

        const formData = new FormData();
        if (requestParameters.image !== undefined) {
            formData.append('image', requestParameters.image as any);
        }

        return this.request<object>({
            path: `/image/text/asciify/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formData,
        });
    }

    /**
     * Get list of models available for asciify
     */
    getVersionsImageTextAsciifyGet(): Observable<object> {
        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        return this.request<object>({
            path: `/image/text/asciify/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyImageTextAsciifyPostModelEnum {
    RameshAditya = 'ramesh-aditya'
}
