#import <Foundation/Foundation.h>
#import "OAIHTTPValidationError.h"
#import "OAIApi.h"

/**
* FastAPI
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIImageTextOcrApi: NSObject <OAIApi>

extern NSString* kOAIImageTextOcrApiErrorDomain;
extern NSInteger kOAIImageTextOcrApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Apply model for the ocr task for a given models
/// 
///
/// @param image 
/// @param sourceLanguage  (optional) (default to @"en")
/// @param model  (optional) (default to @"easy-ocr")
/// 
///  code:200 message:"Successful Response",
///  code:422 message:"Validation Error"
///
/// @return NSObject*
-(NSURLSessionTask*) applyImageTextOcrPostWithImage: (NSURL*) image
    sourceLanguage: (NSString*) sourceLanguage
    model: (NSString*) model
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Get list of models available for ocr
/// 
///
/// 
///  code:200 message:"Successful Response"
///
/// @return NSObject*
-(NSURLSessionTask*) getVersionsImageTextOcrGetWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;



@end
