#import <Foundation/Foundation.h>
#import "OAIHTTPValidationError.h"
#import "OAIApi.h"

/**
* FastAPI
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIVideoVideoFrameInterpolationApi: NSObject <OAIApi>

extern NSString* kOAIVideoVideoFrameInterpolationApiErrorDomain;
extern NSInteger kOAIVideoVideoFrameInterpolationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Apply model for the frame-interpolation task for a given models
/// 
///
/// @param video 
/// @param model  (optional) (default to @"deep-animation-video-interpolation-in-the-wild")
/// 
///  code:200 message:"Successful Response",
///  code:422 message:"Validation Error"
///
/// @return NSObject*
-(NSURLSessionTask*) applyVideoVideoFrameInterpolationPostWithVideo: (NSURL*) video
    model: (NSString*) model
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Get list of models available for frame-interpolation
/// 
///
/// 
///  code:200 message:"Successful Response"
///
/// @return NSObject*
-(NSURLSessionTask*) getVersionsVideoVideoFrameInterpolationGetWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;



@end
