/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BodyApplyImageImageUncolorizationPost {
    #[serde(rename = "image")]
    pub image: &std::path::Path,
}

impl BodyApplyImageImageUncolorizationPost {
    pub fn new(image: &std::path::Path) -> BodyApplyImageImageUncolorizationPost {
        BodyApplyImageImageUncolorizationPost {
            image: image,
        }
    }
}
