/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BodyApplyVideoVideoFrameInterpolationPost {
    #[serde(rename = "video")]
    pub video: &std::path::Path,
}

impl BodyApplyVideoVideoFrameInterpolationPost {
    pub fn new(video: &std::path::Path) -> BodyApplyVideoVideoFrameInterpolationPost {
        BodyApplyVideoVideoFrameInterpolationPost {
            video: video,
        }
    }
}
