export * from './ImageImageBackgroundRemovalApi';
import { ImageImageBackgroundRemovalApi } from './ImageImageBackgroundRemovalApi';
export * from './ImageImageColorizationApi';
import { ImageImageColorizationApi } from './ImageImageColorizationApi';
export * from './ImageImageFaceBluringApi';
import { ImageImageFaceBluringApi } from './ImageImageFaceBluringApi';
export * from './ImageImageSuperResolutionApi';
import { ImageImageSuperResolutionApi } from './ImageImageSuperResolutionApi';
export * from './ImageImageUncolorizationApi';
import { ImageImageUncolorizationApi } from './ImageImageUncolorizationApi';
export * from './ImageTextAsciifyApi';
import { ImageTextAsciifyApi } from './ImageTextAsciifyApi';
export * from './ImageTextOcrApi';
import { ImageTextOcrApi } from './ImageTextOcrApi';
export * from './TextTextAutocorrectApi';
import { TextTextAutocorrectApi } from './TextTextAutocorrectApi';
export * from './TextTextEmotionRecognitionApi';
import { TextTextEmotionRecognitionApi } from './TextTextEmotionRecognitionApi';
export * from './TextTextEntityExtractionApi';
import { TextTextEntityExtractionApi } from './TextTextEntityExtractionApi';
export * from './TextTextHateSpeechDetectionApi';
import { TextTextHateSpeechDetectionApi } from './TextTextHateSpeechDetectionApi';
export * from './TextTextKeywordExtractionApi';
import { TextTextKeywordExtractionApi } from './TextTextKeywordExtractionApi';
export * from './TextTextLanguageDetectionApi';
import { TextTextLanguageDetectionApi } from './TextTextLanguageDetectionApi';
export * from './TextTextLanguageGenerationApi';
import { TextTextLanguageGenerationApi } from './TextTextLanguageGenerationApi';
export * from './TextTextLemmatizationApi';
import { TextTextLemmatizationApi } from './TextTextLemmatizationApi';
export * from './TextTextNamedEntityRecognitionApi';
import { TextTextNamedEntityRecognitionApi } from './TextTextNamedEntityRecognitionApi';
export * from './TextTextNextSentencePredictionApi';
import { TextTextNextSentencePredictionApi } from './TextTextNextSentencePredictionApi';
export * from './TextTextNextWordPredictionApi';
import { TextTextNextWordPredictionApi } from './TextTextNextWordPredictionApi';
export * from './TextTextPluralApi';
import { TextTextPluralApi } from './TextTextPluralApi';
export * from './TextTextProgrammingLanguageGenerationApi';
import { TextTextProgrammingLanguageGenerationApi } from './TextTextProgrammingLanguageGenerationApi';
export * from './TextTextQuestionAnsweringApi';
import { TextTextQuestionAnsweringApi } from './TextTextQuestionAnsweringApi';
export * from './TextTextSentenceParaphraserApi';
import { TextTextSentenceParaphraserApi } from './TextTextSentenceParaphraserApi';
export * from './TextTextSentimentAnalysisApi';
import { TextTextSentimentAnalysisApi } from './TextTextSentimentAnalysisApi';
export * from './TextTextSimilarityApi';
import { TextTextSimilarityApi } from './TextTextSimilarityApi';
export * from './TextTextWordAlignmentApi';
import { TextTextWordAlignmentApi } from './TextTextWordAlignmentApi';
export const APIS = [ImageImageBackgroundRemovalApi, ImageImageColorizationApi, ImageImageFaceBluringApi, ImageImageSuperResolutionApi, ImageImageUncolorizationApi, ImageTextAsciifyApi, ImageTextOcrApi, TextTextAutocorrectApi, TextTextEmotionRecognitionApi, TextTextEntityExtractionApi, TextTextHateSpeechDetectionApi, TextTextKeywordExtractionApi, TextTextLanguageDetectionApi, TextTextLanguageGenerationApi, TextTextLemmatizationApi, TextTextNamedEntityRecognitionApi, TextTextNextSentencePredictionApi, TextTextNextWordPredictionApi, TextTextPluralApi, TextTextProgrammingLanguageGenerationApi, TextTextQuestionAnsweringApi, TextTextSentenceParaphraserApi, TextTextSentimentAnalysisApi, TextTextSimilarityApi, TextTextWordAlignmentApi];
