=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/body_apply_image_image_background_removal_post'
require 'openapi_client/models/body_apply_image_image_colorization_post'
require 'openapi_client/models/body_apply_image_image_face_bluring_post'
require 'openapi_client/models/body_apply_image_image_restoration_post'
require 'openapi_client/models/body_apply_image_image_super_resolution_post'
require 'openapi_client/models/body_apply_image_image_uncolorization_post'
require 'openapi_client/models/body_apply_image_text_asciify_post'
require 'openapi_client/models/body_apply_image_text_ocr_post'
require 'openapi_client/models/body_apply_video_video_frame_interpolation_post'
require 'openapi_client/models/http_validation_error'
require 'openapi_client/models/validation_error'

# APIs
require 'openapi_client/api/image_image_background_removal_api'
require 'openapi_client/api/image_image_colorization_api'
require 'openapi_client/api/image_image_face_bluring_api'
require 'openapi_client/api/image_image_restoration_api'
require 'openapi_client/api/image_image_super_resolution_api'
require 'openapi_client/api/image_image_uncolorization_api'
require 'openapi_client/api/image_text_asciify_api'
require 'openapi_client/api/image_text_ocr_api'
require 'openapi_client/api/text_text_autocorrect_api'
require 'openapi_client/api/text_text_boolean_question_generation_api'
require 'openapi_client/api/text_text_dependency_tracking_api'
require 'openapi_client/api/text_text_emotion_recognition_api'
require 'openapi_client/api/text_text_entity_extraction_api'
require 'openapi_client/api/text_text_hate_speech_detection_api'
require 'openapi_client/api/text_text_keyword_extraction_api'
require 'openapi_client/api/text_text_language_detection_api'
require 'openapi_client/api/text_text_language_generation_api'
require 'openapi_client/api/text_text_lemmatization_api'
require 'openapi_client/api/text_text_named_entity_recognition_api'
require 'openapi_client/api/text_text_next_sentence_prediction_api'
require 'openapi_client/api/text_text_next_word_prediction_api'
require 'openapi_client/api/text_text_plural_api'
require 'openapi_client/api/text_text_programming_language_generation_api'
require 'openapi_client/api/text_text_programming_language_identification_api'
require 'openapi_client/api/text_text_question_answering_api'
require 'openapi_client/api/text_text_sentence_pair_modeling_api'
require 'openapi_client/api/text_text_sentence_paraphraser_api'
require 'openapi_client/api/text_text_sentiment_analysis_api'
require 'openapi_client/api/text_text_similarity_api'
require 'openapi_client/api/text_text_summarization_api'
require 'openapi_client/api/text_text_translation_api'
require 'openapi_client/api/text_text_transliteration_api'
require 'openapi_client/api/text_text_word_alignment_api'
require 'openapi_client/api/video_video_frame_interpolation_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
