//
// BodyApplyVideoVideoFrameInterpolationPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class BodyApplyVideoVideoFrameInterpolationPost: JSONEncodable {

    public var video: URL?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["video"] = self.video?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

