/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.io.File;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BodyApplyVideoVideoFrameInterpolationPost {
  
  @SerializedName("video")
  private File video = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public File getVideo() {
    return video;
  }
  public void setVideo(File video) {
    this.video = video;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyApplyVideoVideoFrameInterpolationPost bodyApplyVideoVideoFrameInterpolationPost = (BodyApplyVideoVideoFrameInterpolationPost) o;
    return (this.video == null ? bodyApplyVideoVideoFrameInterpolationPost.video == null : this.video.equals(bodyApplyVideoVideoFrameInterpolationPost.video));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.video == null ? 0: this.video.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyApplyVideoVideoFrameInterpolationPost {\n");
    
    sb.append("  video: ").append(video).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
