/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BodyApplyVideoVideoFrameInterpolationPost model module.
 * @module model/BodyApplyVideoVideoFrameInterpolationPost
 * @version 0.1.0
 */
class BodyApplyVideoVideoFrameInterpolationPost {
    /**
     * Constructs a new <code>BodyApplyVideoVideoFrameInterpolationPost</code>.
     * @alias module:model/BodyApplyVideoVideoFrameInterpolationPost
     * @param video {File} 
     */
    constructor(video) { 
        
        BodyApplyVideoVideoFrameInterpolationPost.initialize(this, video);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, video) { 
        obj['video'] = video;
    }

    /**
     * Constructs a <code>BodyApplyVideoVideoFrameInterpolationPost</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodyApplyVideoVideoFrameInterpolationPost} obj Optional instance to populate.
     * @return {module:model/BodyApplyVideoVideoFrameInterpolationPost} The populated <code>BodyApplyVideoVideoFrameInterpolationPost</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodyApplyVideoVideoFrameInterpolationPost();

            if (data.hasOwnProperty('video')) {
                obj['video'] = ApiClient.convertToType(data['video'], File);
            }
        }
        return obj;
    }


}

/**
 * @member {File} video
 */
BodyApplyVideoVideoFrameInterpolationPost.prototype['video'] = undefined;






export default BodyApplyVideoVideoFrameInterpolationPost;

