/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BodyApplyImageTextAsciifyPost model module.
 * @module model/BodyApplyImageTextAsciifyPost
 * @version 0.1.0
 */
class BodyApplyImageTextAsciifyPost {
    /**
     * Constructs a new <code>BodyApplyImageTextAsciifyPost</code>.
     * @alias module:model/BodyApplyImageTextAsciifyPost
     * @param image {File} 
     */
    constructor(image) { 
        
        BodyApplyImageTextAsciifyPost.initialize(this, image);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, image) { 
        obj['image'] = image;
    }

    /**
     * Constructs a <code>BodyApplyImageTextAsciifyPost</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodyApplyImageTextAsciifyPost} obj Optional instance to populate.
     * @return {module:model/BodyApplyImageTextAsciifyPost} The populated <code>BodyApplyImageTextAsciifyPost</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodyApplyImageTextAsciifyPost();

            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], File);
            }
        }
        return obj;
    }


}

/**
 * @member {File} image
 */
BodyApplyImageTextAsciifyPost.prototype['image'] = undefined;






export default BodyApplyImageTextAsciifyPost;

