/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBody_apply_video_video_frame_interpolation__post.h
 *
 * 
 */

#ifndef OAIBody_apply_video_video_frame_interpolation__post_H
#define OAIBody_apply_video_video_frame_interpolation__post_H

#include <QJsonObject>


#include "OAIHttpRequest.h"

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIBody_apply_video_video_frame_interpolation__post: public OAIObject {
public:
    OAIBody_apply_video_video_frame_interpolation__post();
    OAIBody_apply_video_video_frame_interpolation__post(QString json);
    ~OAIBody_apply_video_video_frame_interpolation__post() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAIHttpRequestInputFileElement* getVideo() const;
    void setVideo(const OAIHttpRequestInputFileElement* &video);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAIHttpRequestInputFileElement* video;
    bool m_video_isSet;
    bool m_video_isValid;
    
    };

}

#endif // OAIBody_apply_video_video_frame_interpolation__post_H
