/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIImageTextAsciifyApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAIImageTextAsciifyApi::OAIImageTextAsciifyApi() {

}

OAIImageTextAsciifyApi::~OAIImageTextAsciifyApi() {

}

OAIImageTextAsciifyApi::OAIImageTextAsciifyApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAIImageTextAsciifyApi::applyImageTextAsciifyPost(const OAIHttpRequestInputFileElement*& image, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/image/text/asciify/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");
    if (image != nullptr) {
        input.add_file("image", (*image).local_filename, (*image).request_filename, (*image).mime_type);
    }
    

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAIImageTextAsciifyApi::applyImageTextAsciifyPostCallback);

    worker->execute(&input);
}

void
OAIImageTextAsciifyApi::applyImageTextAsciifyPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyImageTextAsciifyPostSignal(output);
        emit applyImageTextAsciifyPostSignalFull(worker, output);
    } else {
        emit applyImageTextAsciifyPostSignalE(output, error_type, error_str);
        emit applyImageTextAsciifyPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAIImageTextAsciifyApi::getVersionsImageTextAsciifyGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/image/text/asciify/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAIImageTextAsciifyApi::getVersionsImageTextAsciifyGetCallback);

    worker->execute(&input);
}

void
OAIImageTextAsciifyApi::getVersionsImageTextAsciifyGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsImageTextAsciifyGetSignal(output);
        emit getVersionsImageTextAsciifyGetSignalFull(worker, output);
    } else {
        emit getVersionsImageTextAsciifyGetSignalE(output, error_type, error_str);
        emit getVersionsImageTextAsciifyGetSignalEFull(worker, error_type, error_str);
    }
}


}
