/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIImageTextOcrApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAIImageTextOcrApi::OAIImageTextOcrApi() {

}

OAIImageTextOcrApi::~OAIImageTextOcrApi() {

}

OAIImageTextOcrApi::OAIImageTextOcrApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAIImageTextOcrApi::applyImageTextOcrPost(const OAIHttpRequestInputFileElement*& image, const QString& source_language, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/image/text/ocr/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("source_language"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(source_language)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");
    if (image != nullptr) {
        input.add_file("image", (*image).local_filename, (*image).request_filename, (*image).mime_type);
    }
    

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAIImageTextOcrApi::applyImageTextOcrPostCallback);

    worker->execute(&input);
}

void
OAIImageTextOcrApi::applyImageTextOcrPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyImageTextOcrPostSignal(output);
        emit applyImageTextOcrPostSignalFull(worker, output);
    } else {
        emit applyImageTextOcrPostSignalE(output, error_type, error_str);
        emit applyImageTextOcrPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAIImageTextOcrApi::getVersionsImageTextOcrGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/image/text/ocr/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAIImageTextOcrApi::getVersionsImageTextOcrGetCallback);

    worker->execute(&input);
}

void
OAIImageTextOcrApi::getVersionsImageTextOcrGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsImageTextOcrGetSignal(output);
        emit getVersionsImageTextOcrGetSignalFull(worker, output);
    } else {
        emit getVersionsImageTextOcrGetSignalE(output, error_type, error_str);
        emit getVersionsImageTextOcrGetSignalEFull(worker, error_type, error_str);
    }
}


}
