/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIVideoVideoFrameInterpolationApi_H
#define OAI_OAIVideoVideoFrameInterpolationApi_H

#include "OAIHttpRequest.h"

#include "OAIHTTPValidationError.h"
#include "OAIHttpRequest.h"
#include "OAIObject.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OAIVideoVideoFrameInterpolationApi: public QObject {
    Q_OBJECT

public:
    OAIVideoVideoFrameInterpolationApi();
    OAIVideoVideoFrameInterpolationApi(QString host, QString basePath);
    ~OAIVideoVideoFrameInterpolationApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void applyVideoVideoFrameInterpolationPost(const OAIHttpRequestInputFileElement*& video, const QString& model);
    void getVersionsVideoVideoFrameInterpolationGet();
    
private:
    void applyVideoVideoFrameInterpolationPostCallback (OAIHttpRequestWorker * worker);
    void getVersionsVideoVideoFrameInterpolationGetCallback (OAIHttpRequestWorker * worker);
    
signals:
    void applyVideoVideoFrameInterpolationPostSignal(OAIObject summary);
    void getVersionsVideoVideoFrameInterpolationGetSignal(OAIObject summary);
    
    void applyVideoVideoFrameInterpolationPostSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    void getVersionsVideoVideoFrameInterpolationGetSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    
    void applyVideoVideoFrameInterpolationPostSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsVideoVideoFrameInterpolationGetSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void applyVideoVideoFrameInterpolationPostSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsVideoVideoFrameInterpolationGetSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
