//
// ImageTextOcrAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class ImageTextOcrAPI: APIBase {
    /**
     * enum for parameter model
     */
    public enum Model_applyImageTextOcrPost: String { 
        case TesseractDefault = "tesseract-default"
        case TesseractDenoising = "tesseract-denoising"
        case EasyOcr = "easy-ocr"
    }

    /**
     Apply model for the ocr task for a given models
     
     - parameter image: (form)  
     - parameter sourceLanguage: (query)  (optional)
     - parameter model: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func applyImageTextOcrPost(image image: NSURL, sourceLanguage: String? = nil, model: Model_applyImageTextOcrPost? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        applyImageTextOcrPostWithRequestBuilder(image: image, sourceLanguage: sourceLanguage, model: model).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Apply model for the ocr task for a given models
     - POST /image/text/ocr/     - parameter image: (form)  
     - parameter sourceLanguage: (query)  (optional)
     - parameter model: (query)  (optional)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func applyImageTextOcrPostWithRequestBuilder(image image: NSURL, sourceLanguage: String? = nil, model: Model_applyImageTextOcrPost? = nil) -> RequestBuilder<AnyObject> {
        let path = "/image/text/ocr/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "source_language": sourceLanguage,
            "model": model?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: falsefalse)
    }

    /**
     Get list of models available for ocr
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getVersionsImageTextOcrGet(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        getVersionsImageTextOcrGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get list of models available for ocr
     - GET /image/text/ocr/
     - returns: RequestBuilder<AnyObject> 
     */
    public class func getVersionsImageTextOcrGetWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/image/text/ocr/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
