//
// VideoVideoFrameInterpolationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class VideoVideoFrameInterpolationAPI: APIBase {
    /**
     Apply model for the frame-interpolation task for a given models
     
     - parameter video: (form)  
     - parameter model: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func applyVideoVideoFrameInterpolationPost(video video: NSURL, model: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        applyVideoVideoFrameInterpolationPostWithRequestBuilder(video: video, model: model).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Apply model for the frame-interpolation task for a given models
     - POST /video/video/frame-interpolation/     - parameter video: (form)  
     - parameter model: (query)  (optional)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func applyVideoVideoFrameInterpolationPostWithRequestBuilder(video video: NSURL, model: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/video/video/frame-interpolation/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "model": model
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: falsefalse)
    }

    /**
     Get list of models available for frame-interpolation
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getVersionsVideoVideoFrameInterpolationGet(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        getVersionsVideoVideoFrameInterpolationGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get list of models available for frame-interpolation
     - GET /video/video/frame-interpolation/
     - returns: RequestBuilder<AnyObject> 
     */
    public class func getVersionsVideoVideoFrameInterpolationGetWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/video/video/frame-interpolation/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
