# FastAPI
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech


#' BodyApplyVideoVideoFrameInterpolationPost Class
#'
#' @field video Video
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BodyApplyVideoVideoFrameInterpolationPost <- R6::R6Class(
  'BodyApplyVideoVideoFrameInterpolationPost',
  public = list(
    `video` = NULL,
    initialize = function(`video`, ...){
      local.optional.var <- list(...)
      if (!missing(`video`)) {
        self$`video` <- `video`
      }
    },
    toJSON = function() {
      BodyApplyVideoVideoFrameInterpolationPostObject <- list()
      if (!is.null(self$`video`)) {
        BodyApplyVideoVideoFrameInterpolationPostObject[['video']] <-
          self$`video`
      }

      BodyApplyVideoVideoFrameInterpolationPostObject
    },
    fromJSON = function(BodyApplyVideoVideoFrameInterpolationPostJson) {
      BodyApplyVideoVideoFrameInterpolationPostObject <- jsonlite::fromJSON(BodyApplyVideoVideoFrameInterpolationPostJson)
      if (!is.null(BodyApplyVideoVideoFrameInterpolationPostObject$`video`)) {
        self$`video` <- BodyApplyVideoVideoFrameInterpolationPostObject$`video`
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "video":
             "%s"
        }',
        self$`video`
      )
    },
    fromJSONString = function(BodyApplyVideoVideoFrameInterpolationPostJson) {
      BodyApplyVideoVideoFrameInterpolationPostObject <- jsonlite::fromJSON(BodyApplyVideoVideoFrameInterpolationPostJson)
      self$`video` <- BodyApplyVideoVideoFrameInterpolationPostObject$`video`
      self
    }
  )
)
