# FastAPI
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech


#' BodyApplyImageTextOcrPost Class
#'
#' @field image Image
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BodyApplyImageTextOcrPost <- R6::R6Class(
  'BodyApplyImageTextOcrPost',
  public = list(
    `image` = NULL,
    initialize = function(`image`, ...){
      local.optional.var <- list(...)
      if (!missing(`image`)) {
        self$`image` <- `image`
      }
    },
    toJSON = function() {
      BodyApplyImageTextOcrPostObject <- list()
      if (!is.null(self$`image`)) {
        BodyApplyImageTextOcrPostObject[['image']] <-
          self$`image`
      }

      BodyApplyImageTextOcrPostObject
    },
    fromJSON = function(BodyApplyImageTextOcrPostJson) {
      BodyApplyImageTextOcrPostObject <- jsonlite::fromJSON(BodyApplyImageTextOcrPostJson)
      if (!is.null(BodyApplyImageTextOcrPostObject$`image`)) {
        self$`image` <- BodyApplyImageTextOcrPostObject$`image`
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "image":
             "%s"
        }',
        self$`image`
      )
    },
    fromJSONString = function(BodyApplyImageTextOcrPostJson) {
      BodyApplyImageTextOcrPostObject <- jsonlite::fromJSON(BodyApplyImageTextOcrPostJson)
      self$`image` <- BodyApplyImageTextOcrPostObject$`image`
      self
    }
  )
)
