# FastAPI
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @title VideoVideoFrameInterpolation operations
#' @description openapi.VideoVideoFrameInterpolation
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' ApplyVideoVideoFrameInterpolationPost Apply model for the frame-interpolation task for a given models
#'
#'
#' GetVersionsVideoVideoFrameInterpolationGet Get list of models available for frame-interpolation
#'
#' }
#'
#' @importFrom caTools base64encode
#' @export
VideoVideoFrameInterpolationApi <- R6::R6Class(
  'VideoVideoFrameInterpolationApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    ApplyVideoVideoFrameInterpolationPost = function(video, model='deep-animation-video-interpolation-in-the-wild', ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`video`)) {
        stop("Missing required parameter `video`.")
      }

      queryParams['model'] <- model

      body <- list(
        "video" = httr::upload_file(video)
      )

      urlPath <- "/video/video/frame-interpolation/"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        object$new()$fromJSONString(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }

    },
    GetVersionsVideoVideoFrameInterpolationGet = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/video/video/frame-interpolation/"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        object$new()$fromJSONString(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }

    }
  )
)
