export * from './imageImageBackgroundRemoval.service';
import { ImageImageBackgroundRemovalService } from './imageImageBackgroundRemoval.service';
export * from './imageImageColorization.service';
import { ImageImageColorizationService } from './imageImageColorization.service';
export * from './imageImageFaceBluring.service';
import { ImageImageFaceBluringService } from './imageImageFaceBluring.service';
export * from './imageImageSuperResolution.service';
import { ImageImageSuperResolutionService } from './imageImageSuperResolution.service';
export * from './imageImageUncolorization.service';
import { ImageImageUncolorizationService } from './imageImageUncolorization.service';
export * from './imageTextAsciify.service';
import { ImageTextAsciifyService } from './imageTextAsciify.service';
export * from './imageTextOcr.service';
import { ImageTextOcrService } from './imageTextOcr.service';
export * from './textTextAutocorrect.service';
import { TextTextAutocorrectService } from './textTextAutocorrect.service';
export * from './textTextEmotionRecognition.service';
import { TextTextEmotionRecognitionService } from './textTextEmotionRecognition.service';
export * from './textTextEntityExtraction.service';
import { TextTextEntityExtractionService } from './textTextEntityExtraction.service';
export * from './textTextHateSpeechDetection.service';
import { TextTextHateSpeechDetectionService } from './textTextHateSpeechDetection.service';
export * from './textTextKeywordExtraction.service';
import { TextTextKeywordExtractionService } from './textTextKeywordExtraction.service';
export * from './textTextLanguageDetection.service';
import { TextTextLanguageDetectionService } from './textTextLanguageDetection.service';
export * from './textTextLanguageGeneration.service';
import { TextTextLanguageGenerationService } from './textTextLanguageGeneration.service';
export * from './textTextLemmatization.service';
import { TextTextLemmatizationService } from './textTextLemmatization.service';
export * from './textTextNamedEntityRecognition.service';
import { TextTextNamedEntityRecognitionService } from './textTextNamedEntityRecognition.service';
export * from './textTextNextSentencePrediction.service';
import { TextTextNextSentencePredictionService } from './textTextNextSentencePrediction.service';
export * from './textTextNextWordPrediction.service';
import { TextTextNextWordPredictionService } from './textTextNextWordPrediction.service';
export * from './textTextPlural.service';
import { TextTextPluralService } from './textTextPlural.service';
export * from './textTextProgrammingLanguageGeneration.service';
import { TextTextProgrammingLanguageGenerationService } from './textTextProgrammingLanguageGeneration.service';
export * from './textTextQuestionAnswering.service';
import { TextTextQuestionAnsweringService } from './textTextQuestionAnswering.service';
export * from './textTextSentenceParaphraser.service';
import { TextTextSentenceParaphraserService } from './textTextSentenceParaphraser.service';
export * from './textTextSentimentAnalysis.service';
import { TextTextSentimentAnalysisService } from './textTextSentimentAnalysis.service';
export * from './textTextSimilarity.service';
import { TextTextSimilarityService } from './textTextSimilarity.service';
export * from './textTextWordAlignment.service';
import { TextTextWordAlignmentService } from './textTextWordAlignment.service';
export const APIS = [ImageImageBackgroundRemovalService, ImageImageColorizationService, ImageImageFaceBluringService, ImageImageSuperResolutionService, ImageImageUncolorizationService, ImageTextAsciifyService, ImageTextOcrService, TextTextAutocorrectService, TextTextEmotionRecognitionService, TextTextEntityExtractionService, TextTextHateSpeechDetectionService, TextTextKeywordExtractionService, TextTextLanguageDetectionService, TextTextLanguageGenerationService, TextTextLemmatizationService, TextTextNamedEntityRecognitionService, TextTextNextSentencePredictionService, TextTextNextWordPredictionService, TextTextPluralService, TextTextProgrammingLanguageGenerationService, TextTextQuestionAnsweringService, TextTextSentenceParaphraserService, TextTextSentimentAnalysisService, TextTextSimilarityService, TextTextWordAlignmentService];
