export * from './imageImageBackgroundRemovalApi';
import { ImageImageBackgroundRemovalApi } from './imageImageBackgroundRemovalApi';
export * from './imageImageColorizationApi';
import { ImageImageColorizationApi } from './imageImageColorizationApi';
export * from './imageImageFaceBluringApi';
import { ImageImageFaceBluringApi } from './imageImageFaceBluringApi';
export * from './imageImageSuperResolutionApi';
import { ImageImageSuperResolutionApi } from './imageImageSuperResolutionApi';
export * from './imageImageUncolorizationApi';
import { ImageImageUncolorizationApi } from './imageImageUncolorizationApi';
export * from './imageTextAsciifyApi';
import { ImageTextAsciifyApi } from './imageTextAsciifyApi';
export * from './imageTextOcrApi';
import { ImageTextOcrApi } from './imageTextOcrApi';
export * from './textTextAutocorrectApi';
import { TextTextAutocorrectApi } from './textTextAutocorrectApi';
export * from './textTextEmotionRecognitionApi';
import { TextTextEmotionRecognitionApi } from './textTextEmotionRecognitionApi';
export * from './textTextEntityExtractionApi';
import { TextTextEntityExtractionApi } from './textTextEntityExtractionApi';
export * from './textTextHateSpeechDetectionApi';
import { TextTextHateSpeechDetectionApi } from './textTextHateSpeechDetectionApi';
export * from './textTextKeywordExtractionApi';
import { TextTextKeywordExtractionApi } from './textTextKeywordExtractionApi';
export * from './textTextLanguageDetectionApi';
import { TextTextLanguageDetectionApi } from './textTextLanguageDetectionApi';
export * from './textTextLanguageGenerationApi';
import { TextTextLanguageGenerationApi } from './textTextLanguageGenerationApi';
export * from './textTextLemmatizationApi';
import { TextTextLemmatizationApi } from './textTextLemmatizationApi';
export * from './textTextNamedEntityRecognitionApi';
import { TextTextNamedEntityRecognitionApi } from './textTextNamedEntityRecognitionApi';
export * from './textTextNextSentencePredictionApi';
import { TextTextNextSentencePredictionApi } from './textTextNextSentencePredictionApi';
export * from './textTextNextWordPredictionApi';
import { TextTextNextWordPredictionApi } from './textTextNextWordPredictionApi';
export * from './textTextPluralApi';
import { TextTextPluralApi } from './textTextPluralApi';
export * from './textTextProgrammingLanguageGenerationApi';
import { TextTextProgrammingLanguageGenerationApi } from './textTextProgrammingLanguageGenerationApi';
export * from './textTextQuestionAnsweringApi';
import { TextTextQuestionAnsweringApi } from './textTextQuestionAnsweringApi';
export * from './textTextSentenceParaphraserApi';
import { TextTextSentenceParaphraserApi } from './textTextSentenceParaphraserApi';
export * from './textTextSentimentAnalysisApi';
import { TextTextSentimentAnalysisApi } from './textTextSentimentAnalysisApi';
export * from './textTextSimilarityApi';
import { TextTextSimilarityApi } from './textTextSimilarityApi';
export * from './textTextWordAlignmentApi';
import { TextTextWordAlignmentApi } from './textTextWordAlignmentApi';
export const APIS = [ImageImageBackgroundRemovalApi, ImageImageColorizationApi, ImageImageFaceBluringApi, ImageImageSuperResolutionApi, ImageImageUncolorizationApi, ImageTextAsciifyApi, ImageTextOcrApi, TextTextAutocorrectApi, TextTextEmotionRecognitionApi, TextTextEntityExtractionApi, TextTextHateSpeechDetectionApi, TextTextKeywordExtractionApi, TextTextLanguageDetectionApi, TextTextLanguageGenerationApi, TextTextLemmatizationApi, TextTextNamedEntityRecognitionApi, TextTextNextSentencePredictionApi, TextTextNextWordPredictionApi, TextTextPluralApi, TextTextProgrammingLanguageGenerationApi, TextTextQuestionAnsweringApi, TextTextSentenceParaphraserApi, TextTextSentimentAnalysisApi, TextTextSimilarityApi, TextTextWordAlignmentApi];
