//
// BodyApplyVideoVideoFrameInterpolationPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class BodyApplyVideoVideoFrameInterpolationPost: JSONEncodable {
    public var video: NSURL?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["video"] = self.video?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
