{-
   FastAPI
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.1.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.BodyApplyVideoVideoFrameInterpolationPost exposing (BodyApplyVideoVideoFrameInterpolationPost, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias BodyApplyVideoVideoFrameInterpolationPost =
    { video : String
    }


decoder : Decoder BodyApplyVideoVideoFrameInterpolationPost
decoder =
    Decode.succeed BodyApplyVideoVideoFrameInterpolationPost
        |> required "video" Decode.string



encode : BodyApplyVideoVideoFrameInterpolationPost -> Encode.Value
encode model =
    Encode.object
        [ ( "video", Encode.string model.video )

        ]


