//
// BodyApplyImageTextOcrPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct BodyApplyImageTextOcrPost: Codable {

    public var image: URL

    public init(image: URL) {
        self.image = image
    }


}

