// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface BodyApplyImageTextAsciifyPost
 */
export interface BodyApplyImageTextAsciifyPost {
    /**
     * 
     * @type {Blob}
     * @memberof BodyApplyImageTextAsciifyPost
     */
    image: Blob;
}

export function BodyApplyImageTextAsciifyPostFromJSON(json: any): BodyApplyImageTextAsciifyPost {
    return {
        'image': json['image'],
    };
}

export function BodyApplyImageTextAsciifyPostToJSON(value?: BodyApplyImageTextAsciifyPost): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'image': value.image,
    };
}


